In [1]:
import numpy

In [2]:
numpy.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=numpy.array([1,2,3,4])


In [4]:
a

array([1, 2, 3, 4])

In [5]:
import numpy as np
a=np.array([45,67,8,9])

In [6]:
a

array([45, 67,  8,  9])

In [7]:
a.size


4

In [8]:
a.shape

(4,)

In [11]:
b=np.array([[1,2],[5,9]])

In [12]:
b

array([[1, 2],
       [5, 9]])

In [13]:
b.size

4

In [14]:
b.shape

(2, 2)

In [15]:
f=np.array([[10,20],[30,40],[50,60]])

In [16]:
f

array([[10, 20],
       [30, 40],
       [50, 60]])

In [17]:
f.size

6

In [18]:
f.shape

(3, 2)

In [19]:
j=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [20]:
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
j.shape

(4, 4)

In [22]:
j.size

16

In [24]:
f=np.array([[1,2],[3,4],[5,6]])

In [25]:
f

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
f.min()

1

In [27]:
f.max()

6

In [28]:
f.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
f

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
g=f.reshape(2,3)

In [35]:
g

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(g)

[[1 2 3]
 [4 5 6]]


In [38]:
f.dtype

dtype('int32')

In [39]:
f.itemsize

4

In [40]:
a=np.array([[1,2],[4,5]],dtype='float64')

In [41]:
a.itemsize

8

In [42]:
a

array([[1., 2.],
       [4., 5.]])

In [43]:
y=np.arange(12)

In [44]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
z=y.reshape(3,4)

In [47]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
x=np.arange(35)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [49]:
a=np.arange(35).reshape(5,7)

In [50]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [51]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [52]:
f=np.array([[1.5,2],[3,4],[5,6]])

In [53]:
f

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [54]:
f=np.array([[1.5,2],[3,4],[5,6]],dtype='int32')

In [55]:
f

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
a=np.arange(5,10)

In [57]:
a

array([5, 6, 7, 8, 9])

In [58]:
a=np.arange(5,50,5)

In [59]:
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [60]:
a=np.array([2,4,6])
b=np.array([3,5,7])
a*b

array([ 6, 20, 42])

In [61]:
a*5

array([10, 20, 30])

In [62]:
a

array([2, 4, 6])

In [63]:
b-a

array([1, 1, 1])

In [64]:
a-b

array([-1, -1, -1])

In [66]:
a=np.random.random([2,3])

In [67]:
a

array([[0.87729431, 0.74521933, 0.07705965],
       [0.61747907, 0.24233871, 0.02836225]])

In [68]:
a=np.ones([2,3])

In [69]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
c=a*b
c

array([[3., 5., 7.],
       [3., 5., 7.]])

In [73]:
c=np.sqrt(b)

In [74]:
c

array([1.73205081, 2.23606798, 2.64575131])

In [78]:
d=np.exp(b)

In [79]:
d

array([  20.08553692,  148.4131591 , 1096.63315843])

In [80]:
e=np.add(a,b)

In [81]:
e

array([[4., 6., 8.],
       [4., 6., 8.]])

In [82]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [83]:
b

array([3, 5, 7])

In [84]:
b[1]

5

In [86]:
b[-3]

3

In [91]:
g=b[0:2]

In [92]:
g

array([3, 5])

In [93]:
a=np.array([1,2,np.nan,4,5,np.nan,7,8])

In [94]:
a

array([ 1.,  2., nan,  4.,  5., nan,  7.,  8.])

In [95]:
b=np.random.rand(2,3)

In [96]:
b

array([[0.13673654, 0.03471761, 0.44231338],
       [0.20724156, 0.62517472, 0.51514106]])

In [97]:
c=np.random.randn(4,5)

In [98]:
c

array([[-0.9160956 , -0.00843022, -1.04173428,  0.22463197, -0.17002817],
       [-0.51412153, -1.00195955, -0.17825837, -0.28494586,  0.87655365],
       [-0.76025939, -1.03228555, -0.19904786, -0.98083506,  0.97658035],
       [-0.51742406,  0.17310458, -0.23867908,  0.23285816, -0.05988462]])