In [2]:
import numpy as np
a=np.array([2,4,6,8,12,9,12])

In [2]:
np.mean(a)

7.571428571428571

In [3]:
np.median(a)

8.0

In [4]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [5]:
txt = "Hello World" [::-1]
print(txt)

dlroW olleH


In [6]:
txt = "Hello World" [::1]
print(txt)

Hello World


In [7]:
p=np.array([[10,20],[30,40]])

In [8]:
p

array([[10, 20],
       [30, 40]])

In [9]:
np.mean(p,axis=0)    #column wise mean will be shown (10+30) / 2   here axis=0 for column and 1 for rows

array([20., 30.])

In [10]:
import statistics as st
st.mode(a)

12

In [14]:
j=np.array([[30,20,30],[30,40,90],[30,120,70]])

In [7]:
print(j)
np.mean(j,axis=0)

[[ 10  20  30]
 [ 30  40  90]
 [ 30 120  70]]


array([23.33333333, 60.        , 63.33333333])

In [8]:
np.mean(j,axis=1)

array([20.        , 53.33333333, 73.33333333])

In [9]:
np.median(j,axis=0)

array([30., 40., 70.])

In [15]:
st.mode(j[0])

30

In [16]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from scipy.stats import percentileofscore

In [17]:
df=pd.read_csv('student_marks.csv')

In [18]:
df

Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05-04-1988     55       45         56       87       21   
1     Suresh      M  04-05-1987     75       96         78       64       90   
2     Ramesh      M  25-05-1989     25       54         89       76       95   
3    Jessica      F  12-08-1990     78       96         86       63       54   
4   Jennifer      F  02-09-1989     58       96         78       46       96   
5       Annu      F  05-04-1988     45       87         52       89       55   
6      pooja      F  04-05-1987     55       64         61       58       75   
7     Ritesh      M  25-05-1989     54       76         87       56       25   
8      Farha      F  12-08-1990     55       63         89       75       78   
9     Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

In [19]:
df['Maths'].mean()

59.6

In [20]:
df['English'].mean()

69.7

In [21]:
df['Maths'].median()

55.0

In [22]:
df['Civics'].median()

63.0

In [23]:
df['Maths'].mode()

0    55
dtype: int64

In [24]:
df['Physics'].mode()

0    96
dtype: int64

In [25]:
b=np.array([3,5,6,9,10])

In [26]:
b.max()

10

In [27]:
b.min()

3

In [28]:
b_range=b.max()-b.min()
b_range

7

In [29]:
np.var(b)

6.640000000000001

In [30]:
np.std(b)

2.5768197453450252

In [33]:
round(np.std(b),3)

2.577