In [1]:
import numpy as np
a=np.array([1,2,3])

In [2]:
type(a)

numpy.ndarray

In [3]:
print(a)

[1 2 3]


In [4]:
a=np.array([[1,2,3],[5,7,8]])
print('\n',a)
print('\n','*' * 30)


 [[1 2 3]
 [5 7 8]]

 ******************************


In [5]:
print('\n',a)


 [[1 2 3]
 [5 7 8]]


In [6]:
a=np.array(np.mat('1,2,3;4,5,6'))
print('\n',a)


 [[1 2 3]
 [4 5 6]]


In [7]:
a=np.array([[1,2,3],[5,7,8]])
print('\n',a)


 [[1 2 3]
 [5 7 8]]


In [8]:
a=[1,3]
b=np.array(a)
print(b)

[1 3]


In [9]:
c=np.asarray(a)
print(c)

[1 3]


In [10]:
c=np.asarray(b)
print(c)

[1 3]


In [11]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print('\n type',type(mat))


 type <class 'numpy.ndarray'>


In [12]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print('\n',mat,'\n')


 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [16]:
print('dimention of matrix = ',mat.ndim,sep="                ")

dimention of matrix =                 2


In [19]:
print('size of matrix = ',mat.size,sep="                ")
print('shape of matrix = ',mat.shape,sep="                ")
print('dtype of matrix = ',mat.dtype,sep="                ")

size of matrix =                 9
shape of matrix =                 (3, 3)
dtype of matrix =                 int32


In [20]:
list(range(2,10.5,0.4))

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
a=np.arange(2,10.5,0.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [23]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [25]:
print("5th element in reverse\n ",np.arange(50,0,-5))

5th element in reverse
  [50 45 40 35 30 25 20 15 10  5]


In [31]:
print("5th element in reverse\n ",np.linspace(10,40,11)) #start , end , no of elements , equal distance no. bw start n end

5th element in reverse
  [10. 13. 16. 19. 22. 25. 28. 31. 34. 37. 40.]


In [36]:
np.linspace(2.0,3.0, num=4, endpoint=True, retstep=False) #endpoint=True will include endpoint

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [39]:
np.linspace(2.0,3.0, num=4, endpoint=True, retstep=True)  #retstep=True will show the distance bw the nos at the end

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [40]:
np.linspace(2.0,3.0, num=4, endpoint=False, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
print(np.ones((5,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [48]:
print(5*np.ones((5,6)))

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [49]:
x=np.arange(30).reshape(3,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [50]:
x=np.arange(31).reshape(3,10) #generated number 31 is not fitting in 3*10=30 size

ValueError: cannot reshape array of size 31 into shape (3,10)

In [56]:
np.random.seed(6)
print('random no with uniform distance/distribution \n')
np.random.rand(10,4)

random no with uniform distance 



array([[0.89286015, 0.33197981, 0.82122912, 0.04169663],
       [0.10765668, 0.59505206, 0.52981736, 0.41880743],
       [0.33540785, 0.62251943, 0.43814143, 0.73588211],
       [0.51803641, 0.5788586 , 0.6453551 , 0.99022427],
       [0.8198582 , 0.41320093, 0.87626766, 0.82375943],
       [0.05447451, 0.71863724, 0.80217056, 0.73640664],
       [0.70913175, 0.54093685, 0.12482417, 0.9576473 ],
       [0.4032563 , 0.21695116, 0.71727585, 0.99420744],
       [0.25561406, 0.67130943, 0.59900591, 0.71733215],
       [0.93734953, 0.35180977, 0.2536341 , 0.40247251]])

In [59]:
np.random.seed(6)
print('random no with normal distribution \n')
print(np.random.randn(10,4))

random no with uniform distance/distribution 

[[-0.31178367  0.72900392  0.21782079 -0.8990918 ]
 [-2.48678065  0.91325152  1.12706373 -1.51409323]
 [ 1.63929108 -0.4298936   2.63128056  0.60182225]
 [-0.33588161  1.23773784  0.11112817  0.12915125]
 [ 0.07612761 -0.15512816  0.63422534  0.810655  ]
 [ 0.35480861  1.81259031 -1.3564758  -0.46363197]
 [ 0.82465384 -1.17643148  1.56448966  0.71270509]
 [-0.1810066   0.53419953 -0.58661296 -1.48185327]
 [ 0.85724762  0.94309899  0.11444143 -0.02195668]
 [-2.12714455 -0.83440747 -0.46550831  0.23371059]]


In [64]:
print('random no random integer vector \n')
print(np.random.randint(5,20,10))                   # numbers bw 5 to 20 total 10 elements

random no random integer vector 

[ 6 16 18 14 15  6 17 19  9  6]


In [66]:
print('random no random integer vector \n')
print(np.random.randint(1,30,(6,7)))                  # numbers bw 1 to 30 to create a matrix of 6 X 7

random no random integer vector 

[[ 9  3 13 21 28  3  6]
 [27 16 26 23 19 12  6]
 [ 6 18  5  6 17  3  3]
 [20 22 29 29 12 26  6]
 [19 27 15 24  9  6  7]
 [11 27 11  4 22 12  2]]


In [68]:
a=np.random.randint(1,40,10)
a

array([ 5, 34, 16,  6, 22,  7,  2, 10, 38, 14])

In [69]:
np.clip(a,a_min=10,a_max=25)               #all element less than 10 will be made 10 and greater than 25 will be made 25

array([10, 25, 16, 10, 22, 10, 10, 10, 25, 14])

In [70]:
np.clip(a,a_min=5,a_max=25)               #all element less than 5 will be made 5 and greater than 25 will be made 25

array([ 5, 25, 16,  6, 22,  7,  5, 10, 25, 14])

In [71]:
print(np.where(a<10))     #shows the index no. of elements which are less than 10 

(array([0, 3, 5, 6], dtype=int64),)


In [73]:
print(np.where(a==34))     #shows the index no. of elements which is equal to 34 , 34 is at 1 index in a arrary above 

(array([1], dtype=int64),)


In [76]:
from numpy.random import randint as ri
a=ri(1,99,30)
print(a)

[61 79 75 59 21 83 71 29 51 70 35 92 29 77 56 47 93 79 86 64 45  2 18 92
  8 86 51 89 96 41]


In [77]:
b=a.reshape(2,3,5)   #2 matrix of 3X5 elements , it is reshaping
print(b)

[[[61 79 75 59 21]
  [83 71 29 51 70]
  [35 92 29 77 56]]

 [[47 93 79 86 64]
  [45  2 18 92  8]
  [86 51 89 96 41]]]


In [79]:
print(b.min())
print(b.max())


2
96


# Sorting

In [86]:
m=ri(1,100,25).reshape(5,5)
print('original matrix \n','-'*50,'\n',m)
print('sorted by row matrix \n','-'*50,'\n',np.sort(m))
print('sorted by column, matrix \n','-'*50,'\n',np.sort(m,axis=0))

original matrix 
 -------------------------------------------------- 
 [[39 43 17 10 22]
 [30 64 96 59 25]
 [67 92 21 35 42]
 [63 37 64 64 49]
 [ 6 27 40 87 98]]
sorted by row matrix 
 -------------------------------------------------- 
 [[10 17 22 39 43]
 [25 30 59 64 96]
 [21 35 42 67 92]
 [37 49 63 64 64]
 [ 6 27 40 87 98]]
sorted by column, matrix 
 -------------------------------------------------- 
 [[ 6 27 17 10 22]
 [30 37 21 35 25]
 [39 43 40 59 42]
 [63 64 64 64 49]
 [67 92 96 87 98]]


# Indexing sort index

In [88]:
arr=np.arange(13,30)
print('array ',arr)

array  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [90]:
print('element at 7th index',arr[7])
print('element 3rd to 5th',arr[3:6])
print('element from 4th index till end',arr[4:])
print('element upto 3rd index from 0th element',arr[:4])

element at 7th index 20
element 3rd to 5th [16 17 18]
element from 4th index till end [17 18 19 20 21 22 23 24 25 26 27 28 29]
element from 4th index till end [13 14 15 16]


In [92]:
print('array ',arr)
print('element in reverse step2 -1 means from las element to everything',arr[-1::-2])

array  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
element in reverse step2 -1 means from las element to everything [29 27 25 23 21 19 17 15 13]


In [94]:
print('element in reverse step -1 means from last element to 7th index from last',arr[-1:-8:-1])

element in reverse step -1 means from last element to 7th index from last [29 28 27 26 25 24 23]


In [95]:
arr=np.arange(0,21,2)
print('new arrar',arr)

new arrar [ 0  2  4  6  8 10 12 14 16 18 20]


In [96]:
print('element 2, 4 and 9 index',arr[[2,4,9]])

element 2, 4 and 9 index [ 4  8 18]


In [98]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
print('1 row and column 2 index data',mat[1][2])

1 row and column 2 index data 6


In [101]:
print('2 index row',mat[2])

2 index row [7 8 9]


In [107]:
print('all rows and column 1 to all',mat[:,1:])

all rows and column 1 to all [[2 3]
 [5 6]
 [8 9]]


In [108]:
print('row 1 and column 1',mat[1:2,1:2])

row 1 and column 1 [[5]]


In [109]:
print('all row but column only 1 and 2\n',mat[0:2,[1,2]])

all row but column only 1 and 2
 [[2 3]
 [5 6]]


In [112]:
print(mat)
mat[0,1]=200
print('\n',mat)

[[  1 500   3]
 [  4   5   6]
 [  7   8   9]]

 [[  1 200   3]
 [  4   5   6]
 [  7   8   9]]
